### ISSUE TITLE
The name 'Container' is not very user-friendly when used in flutter Widgets

### ISSUE THREAD

**Issue by maartenvang** [vanlooverenkoen/kiwi#12]
When using the `Container` in a file that imports `package:flutter/material.dart`, using the kiwi Container becomes a challenge.

An easy solution is to use a named import e.g. `import 'package:kiwi/kiwi.dart' as kiwi;` and then use `kiwi.Container()`. But I still think that, since Flutter is a big use case for Dart, choosing a different name would be a valid decision.

**Comment by vanlooverenkoen** [comment]
This should be renamed. because autoimports with Flutter and Kiwi can not be used

**Comment by sosite** [comment]
Right now I workaround it by create own wrapper on `Container` class ;)
```dart
class Di {
  Di._();

  static final Container _kiwi = Container();

  /// Attempts to resolve the type [T].
  ///
  /// If [name] is set, the instance or builder registered with this
  /// name will be get.
  static T resolve<T>([String name]) => _kiwi.resolve<T>(name);
}
```

**Comment by vanlooverenkoen** [comment]
From version 1.0.0 Container will be renamed to KiwiContainer to make it easier for flutter developers. I am currently working on the implementation for kiwi and the kiwi_generator

**Comment by vanlooverenkoen** [comment]
**Breaking Change** in kiwi 1.0.0 & kiwi_generator 1.0.0
