### ISSUE TITLE
Generated Injector is private

### ISSUE THREAD

**Issue by mps2209** [vanlooverenkoen/kiwi#17]
After generating the injector.g.dart the class name is _$Injector and therefore cant by referenced in another dart file. I have to manually remove the underline

**Comment by sosite** [comment]
@mps2209 In your main `Injector` lib just add this lines:
```dart
part 'your_injector.g.dart';

Injector getInjector() => _$Injector();
```
But yea, for me it's also a little code smell. Or not? 🤔

**Comment by gurleensethi** [comment]
As the docs suggest you can create a `setup` method in you `Injector` class that would initialize(`configure`) your injector. You don't need the `_$Injector` class anywhere else.

**Comment by vanlooverenkoen** [comment]
@mps2209 Generated classes should not be used outside the class itself. `_$` indicates it is a generated class. 

If you want to use it outside of this class. You can do 2 things:
**Add a factory:**
   ```
     factory Injector() = _$Injector;
   ```
**Add an extra method in the same file of your Injector**
Future<void> setupNetworkingDependencies() async {
  final injector = _$Injector()
  injector.registerNetworkDependencies();
  injector.registerWebservices();
  // other dependencies
}

The last example is what I use most of the time. You can wrap it in an extra class if you don't want to be using the method directly. But this way you have a clear overview of all your dependency setup methods

Please reopen if you still have questions
