### ISSUE TITLE
The type String was not registered 

### ISSUE THREAD

**Issue by timeshift92** [vanlooverenkoen/kiwi#24]
The type String was not registered
'package:kiwi/src/container.dart':
Failed assertion: line 92 pos 12: 'silent || (providers?.containsKey(T) ?? false)'
hello how can i resolve this problem?

**Comment by vanlooverenkoen** [comment]
Can you provide me with a working small working example where you have this problem?

**Comment by vanlooverenkoen** [comment]
#32 in now released in kiw 1.1.0. Maybe you can check better what you are doing wrong there?

**Comment by vanlooverenkoen** [comment]
Closed because of inactivity. Comment if you still want to have this issue reopened
