### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by britannio** [vanlooverenkoen/kiwi#27]
The last update was a year ago, maybe it should be marked as discontinued on pub or new maintainers should be assigned?

**Comment by vanlooverenkoen** [comment]
I have emailed him a couple months ago. No response

**Comment by letsar** [comment]
Sorry for the delay, I didn't take the time to answer this.
I don't have have enough time to maintain all the packages that need it for the moment and I'm currently experimenting another way to manage the state in Flutter.
I can give the repo to someone else if you want, but I would need to read how to do that on pub.dev also.

**Comment by vanlooverenkoen** [comment]
I have send you an email with the details for a transfer

**Comment by vanlooverenkoen** [comment]
I have taken over the maintenance from @letsar 
kiwi 0.3.0 & kiwi_generator 0.5.0 are now available with the version fixes
