### ISSUE TITLE
Register Type from imported package

### ISSUE THREAD

**Issue by as001622** [vanlooverenkoen/kiwi#5]
Hello! 
How to register some Type from imported package, which doesn't have a constructor, but instead has a getInstance() method, witch return Future<Type>. As example SharedPreferences.

**Comment by vanlooverenkoen** [comment]
@as001622 what @letsar said is indeed correct you should do something like this:
```
final myInstance = await YourClass.getFuture();
container.registerInstance(myInstance);
```

If you still have questions about this, feel free to comment, reopen the ticket.
