### ISSUE TITLE
Add support for nullability

### ISSUE THREAD

**Issue by vanlooverenkoen** [vanlooverenkoen/kiwi#51]
#49 does not yet support nullability.

With the testing/stable release closing for nullability, we need to make sure kiwi supports nullability as well

**Comment by vanlooverenkoen** [comment]
@Yegorisa I will take a look at it tomorrow

**Comment by vanlooverenkoen** [comment]
I have already migrated the kiwi package to support nullability. (In it's most basic form, just migrated to support nullsafety) the kiwi_generator has some dependencies that are not yet supporting nullsafety so for that one I will still wait.

**Comment by vanlooverenkoen** [comment]
@Yegorisa Since we are blocked because of the dart-lang packages. Do you think it would be nice to already have a kiwi-nullsafety.0 release? This release will not work with the kiwi_genrator.

**Comment by Yegorisa** [comment]
@vanlooverenkoen since I am using the Kiwi with the kiwi_generator, I would prefer to wait for until dart sdk will migrate and then migrate kiwi_generator

**Comment by behnamsattar** [comment]
Null safety is out with Flutter 2.0 and this needs to be addressed ASAP.

**Comment by vanlooverenkoen** [comment]
I was still waiting on the nullsafe support for some dependencies. As stated before kiwi is already migrated. You can use it via git right now

**Comment by vanlooverenkoen** [comment]
@Yegorisa @behnamsattar I have created a pull request with the fixes for null safety. Because I was hoping the generator could be migrated to null safety as wel. I will create a dev release today for kiwi & the generator. 

Please file new issues when you are having trouble.
