### ISSUE TITLE
between kiwi and flutter_test version solving failed. issue

### ISSUE THREAD

**Issue by gkneshan** [vanlooverenkoen/kiwi#53]
i try to use kiwi 2.0.1 in my flutter project. but pubspec.yaml gives error as 
![Screenshot from 2020-10-10 14-36-45](https://user-images.githubusercontent.com/11815178/95651182-21389e00-0b06-11eb-9947-e580024c8864.png)
![Screenshot from 2020-10-10 14-36-57](https://user-images.githubusercontent.com/11815178/95651188-2a296f80-0b06-11eb-9266-6c7efe4b9e9b.png)

**Comment by vanlooverenkoen** [comment]
Flutter_test is not using the latest meta version. Kiwi is. So you have to add this to specifically define what version should be used

```
dependency_overrides:
  meta: 1.2.3
```

**Comment by gkneshan** [comment]
thanks a lot  @vanlooverenkoen .
it's working...
thank you
