### ISSUE TITLE
Usage of generics is wrong

### ISSUE THREAD

**Issue by dalewking** [vanlooverenkoen/kiwi#9]
Looking at the implementation, e.g.:

```
  void registerInstance<S, T extends S>(
    S instance, {
    String name,
  }) {
    _setProvider(name, _Provider<S>.instance(instance));
  }
```

The use of generics here is not really correct. There are 2 type parameters, but the T type parameter is not actually used in the code. Shouldn't the T type parameter just be removed?

So if you have class B that extends class A and I want to register an instance of class B but using type A, I have to say:

    container.resgisterInstance<A, B>( bInstance);

which doesn't seem that onerous with single letter class names, but with generic types this is ridiculously verbose.

If the T parameter is removed, I should be able to do that simply as:

    container.resgisterInstance<A>(bInstance);

**Comment by itavero** [comment]
Besides that, I actually think that the current interface is a bit confusing (also for `registerFactory` and `registerSingleton`).

Especially considering that the [blog post announcing Kiwi](https://medium.com/flutter-community/announcing-kiwi-52ddb3935e6d) isn't really mentioning what resolving dependencies that are registered in this way looks like. 

First, this interface is used to register an instance:
```dart
// Registers a new factory, with a specified name, and under a supertype.
container.registerFactory<Character, Sith>((c) => Sith('Anakin', 'Skywalker'), name: 'DartVader');
```

Later on, the following code is shown to retrieve an instance:
```dart
// Gets the instance registered for the Sith type under 'DartVader' name.
Sith dartVader = container.resolve<Sith>('DartVader');
```

However, considering the registration mentioned above, I would expect to use:
```dart
// Gets the instance registered for the Sith type under 'DartVader' name.
Character dartVader = container.resolve<Character>('DartVader');
```

**Comment by vanlooverenkoen** [comment]
@itavero 
> Later on, the following code is shown to retrieve an instance:
> 
> ```dart
> // Gets the instance registered for the Sith type under 'DartVader' name.
> Sith dartVader = container.resolve<Sith>('DartVader');
> ```

This is indeed not correct. If you would test this. It would cause an error because Sith is never registered. 

> However, considering the registration mentioned above, I would expect to use:
> 
> ```dart
> // Gets the instance registered for the Sith type under 'DartVader' name.
> Character dartVader = container.resolve<Character>('DartVader');
> ```

This is indeed correct.

**Comment by vanlooverenkoen** [comment]
@dalewking I will take a look at the register instance. But at first sight it looks like the T can be removed. It is needed for the annotation though. But not for the method itself

**Comment by vanlooverenkoen** [comment]
@itavero #36 can be used to resolveAs

**Comment by vanlooverenkoen** [comment]
@itavero & @dalewking if you want to review pull request: #38.

**Comment by dalewking** [comment]
nice to see some action on this finally after 15 months

**Comment by vanlooverenkoen** [comment]
Yes indeed. I have taken over the maintenance of kiwi. We are using this package for more than a year now. So I am really dedicated to keeping this package up-to-date. I went through all the issues this weekend.

**Comment by vanlooverenkoen** [comment]
Fixed in
kiwi => 2.0.0
kiwi_generator => 2.0.0

**Comment by dalewking** [comment]
Noticed that Readme is slightly misleading on this now, it says (unchanged from before):

> By default instances are registered under their type. If you want to register an instance under a supertype, you have to specify both of them:

It would be more accurate to say that "you have to specify the supertype"
